<a href="https://colab.research.google.com/github/jashpal37/CE007_ML_Practical/blob/master/LAB03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1_NB_Classifier_Weather

In [1]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [2]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

In [3]:
#create labelEncoder
le = preprocessing.LabelEncoder()

#converting string labels into numbers
weather_encoded = le.fit_transform(weather)
print("Weather :",weather_encoded)

temp_encoded = le.fit_transform(temp)
print("Temp :",temp_encoded)

label = le.fit_transform(play)
print("Play :",label)

Weather : [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp : [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play : [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [4]:
#combining weather and temp into single listof tuple
features = tuple(zip(weather_encoded,temp_encoded))
print("Features :",features)

Features : ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [5]:
#create classifier
model = MultinomialNB()

#train the model using the training sets
model.fit(features,label)

MultinomialNB()

In [6]:

#predict output
predicted = model.predict([[0,1]]) #0:overcast,1:Hot
print("Predicted Value:",predicted)

predicted= model.predict([[2,2]]) #2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]
Predicted Value: [1]


# 2_NB_Classifier_Iris

In [7]:
import numpy as np
from sklearn import datasets

#Load dataset
iris = datasets.load_iris()

In [8]:
print("Features :",iris.feature_names)
print("\nLabels :",iris.target_names)
print("\nData Shape: ",iris.data.shape)
print("\nData: ",iris.data)
print("\nTarget Shape: ",iris.target.shape)
print("\nTarget: ",iris.target)
print("\nData Type: ",type(iris.data))

newdata = iris.data[50:,:]
newtarget = iris.target[50:]

print("\nNew Data Shape: ",newdata.shape)
print("\nNew Target Shape: ",newtarget.shape)

Features : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Labels : ['setosa' 'versicolor' 'virginica']

Data Shape:  (150, 4)

Data:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.

In [9]:
from sklearn.model_selection import train_test_split

data_train,data_test,target_train,target_test = train_test_split(newdata,newtarget,test_size=0.30,random_state=53)

In [10]:
gnb = GaussianNB()
gnb.fit(data_train,target_train)
target_pred = gnb.predict(data_test)

In [11]:
from sklearn import metrics
print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))

Accuracy:  0.9666666666666667


In [12]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test,target_pred)

array([[13,  0],
       [ 1, 16]])

In [13]:
from sklearn.metrics import precision_score,recall_score
precision = precision_score(target_test,target_pred)
print('pricision: {}'.format(precision))
recall = recall_score(target_test,target_pred)
print('recall: {}'.format(recall))

pricision: 0.9285714285714286
recall: 1.0


# 3_NB_Classifier_Iris

# Task - 1

In [14]:
import pandas as pd
import numpy as np
import io
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.naive_bayes import GaussianNB,MultinomialNB


In [16]:
from google.colab import files
uploaded = files.upload()
datasets = pd.read_csv(io.BytesIO(uploaded['Dataset2.csv']))
datasets = pd.read_csv("Dataset2.csv")

Saving Dataset2.csv to Dataset2.csv


In [18]:
datasets

Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N

In [19]:
le = LabelEncoder()
X=datasets.iloc[:,:-1].values
Y=datasets.iloc[:,-1].values

In [20]:
outlook_encoded=le.fit_transform(X[:,0])

In [21]:
outlook_encoded

array([1, 1, 0, 2, 2, 2, 0, 1, 1, 2, 1, 0, 0, 2])

In [22]:
temp_encoded=le.fit_transform(X[:,1])

In [23]:
temp_encoded

array([1, 1, 1, 2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2])

In [24]:
Wind_encoded=le.fit_transform(X[:,2])

In [25]:
Wind_encoded

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1])

In [26]:
humidity_encoded=le.fit_transform(X[:,3])

In [27]:
humidity_encoded

array([2, 0, 2, 2, 2, 1, 2, 2, 1, 0, 0, 1, 2, 2])

In [28]:
Y

array(['N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N'], dtype=object)

In [29]:
features= np.array(list(zip(outlook_encoded,temp_encoded,Wind_encoded,humidity_encoded)),dtype=object)

print("Features: ", features)
print("Target: ",Y)

Features:  [[1 1 0 2]
 [1 1 1 0]
 [0 1 0 2]
 [2 2 0 2]
 [2 2 0 2]
 [2 2 1 1]
 [0 0 1 2]
 [1 0 0 2]
 [1 0 0 1]
 [2 2 0 0]
 [1 2 1 0]
 [0 2 1 1]
 [0 1 0 2]
 [2 2 1 2]]
Target:  ['N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N']


In [30]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(features,
Y, test_size = 0.1, random_state = 53)
print(data_train.shape,target_train.shape)

(12, 4) (12,)


In [31]:
data_test

array([[2, 2, 0, 2],
       [1, 0, 0, 2]], dtype=object)

In [32]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [33]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.5


In [34]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.  0.5]
recall: [0. 1.]


/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Nor-
mal’, and Wind = ’False’?**bold text**

In [35]:
pre=[1,2,2,0]
np.array(pre).reshape(1,-1)

array([[1, 2, 2, 0]])

In [36]:
gnb.predict(np.array(pre).reshape(1,-1))

array(['N'], dtype='<U1')

In [37]:
gnb.predict_proba(np.array(pre).reshape(1,-1))

array([[0.53514985, 0.46485015]])

(2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,
and Wind = ’True’?**bold text**

In [38]:
pre=[2,0,0,1]
np.array(pre).reshape(1,-1)

array([[2, 0, 0, 1]])

In [39]:
gnb.predict(np.array(pre).reshape(1,-1))

array(['Y'], dtype='<U1')

In [40]:
gnb.predict_proba(np.array(pre).reshape(1,-1))

array([[0.02810552, 0.97189448]])

# Task:2

In [41]:
import sklearn
from sklearn import datasets
digit_data = sklearn.datasets.load_digits();
features = digit_data.feature_names
targets = digit_data.target_names
print(digit_data.feature_names)

['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1', 'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6', 'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3', 'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7']


In [42]:
df=pd.DataFrame(digit_data.data, columns=digit_data.feature_names)
df["target"]=pd.Series(digit_data.target)

In [43]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [44]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(digit_data.data,
digit_data.target, test_size = 0.35, random_state = 53)
print(data_test)
data_train

[[ 0.  0.  1. ... 12.  7.  0.]
 [ 0.  0.  2. ... 10.  0.  0.]
 [ 0.  0.  4. ...  4.  0.  0.]
 ...
 [ 0.  0.  9. ... 15.  4.  0.]
 [ 0.  1. 13. ... 11.  4.  0.]
 [ 0.  2. 12. ...  0.  0.  0.]]


array([[ 0.,  0.,  6., ..., 16., 16., 12.],
       [ 0.,  0.,  0., ..., 13.,  1.,  0.],
       [ 0.,  0.,  0., ...,  9.,  0.,  0.],
       ...,
       [ 0.,  1., 15., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.]])

In [45]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)
target_pred

array([6, 8, 1, 6, 1, 3, 8, 5, 8, 4, 7, 8, 1, 8, 8, 8, 8, 9, 6, 3, 2, 6,
       8, 7, 8, 9, 9, 7, 3, 8, 7, 1, 4, 0, 8, 0, 5, 6, 1, 0, 3, 0, 7, 8,
       2, 1, 8, 5, 6, 7, 5, 4, 4, 7, 7, 9, 1, 8, 5, 5, 3, 5, 7, 9, 7, 8,
       7, 4, 3, 5, 1, 3, 7, 8, 8, 8, 3, 7, 8, 8, 5, 5, 7, 2, 1, 2, 2, 1,
       5, 5, 5, 4, 3, 1, 4, 2, 5, 8, 7, 0, 4, 7, 7, 5, 8, 8, 2, 8, 7, 3,
       1, 7, 3, 8, 9, 4, 4, 2, 0, 5, 6, 0, 2, 8, 8, 1, 4, 3, 2, 7, 0, 7,
       9, 3, 8, 7, 8, 8, 8, 8, 6, 9, 8, 8, 1, 9, 0, 7, 6, 2, 9, 4, 5, 8,
       8, 8, 4, 5, 4, 1, 8, 6, 7, 5, 1, 9, 0, 8, 6, 4, 9, 0, 8, 8, 6, 5,
       8, 4, 8, 7, 2, 6, 8, 2, 8, 8, 8, 6, 8, 7, 5, 3, 9, 9, 5, 8, 8, 7,
       2, 0, 2, 8, 1, 2, 7, 3, 8, 8, 1, 7, 3, 5, 0, 6, 8, 8, 8, 8, 5, 5,
       0, 0, 2, 6, 6, 2, 7, 6, 5, 0, 4, 2, 0, 7, 8, 0, 8, 5, 2, 7, 5, 6,
       5, 1, 7, 8, 8, 2, 1, 8, 8, 0, 7, 8, 0, 5, 5, 5, 6, 7, 8, 8, 8, 6,
       8, 3, 8, 1, 6, 7, 7, 1, 5, 5, 8, 4, 0, 8, 6, 5, 0, 5, 9, 9, 4, 8,
       8, 2, 5, 4, 3, 4, 5, 0, 6, 2, 8, 7, 9, 1, 8,

In [46]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.8394276629570747


In [47]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[48,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 46,  0,  0,  0,  0,  2,  0, 12,  2],
       [ 0,  4, 39,  1,  0,  1,  0,  0, 18,  0],
       [ 0,  0,  1, 41,  0,  5,  0,  2, 11,  1],
       [ 0,  0,  0,  0, 55,  0,  0,  7,  4,  0],
       [ 0,  0,  0,  0,  0, 60,  1,  1,  3,  0],
       [ 0,  1,  0,  0,  0,  2, 63,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 67,  0,  0],
       [ 0,  2,  0,  1,  0,  0,  0,  1, 72,  0],
       [ 1,  1,  0,  2,  0,  2,  0,  6,  6, 37]])

In [48]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.97959184 0.85185185 0.975      0.91111111 1.         0.85714286
 0.95454545 0.79761905 0.57142857 0.925     ]
recall: [1.         0.74193548 0.61904762 0.67213115 0.83333333 0.92307692
 0.95454545 1.         0.94736842 0.67272727]
