In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [2]:
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

In [3]:
lr=linear_model.LogisticRegression()
dt=DecisionTreeClassifier()
bn=BernoulliNB()

In [4]:
df=pd.DataFrame(Data.data, columns=Data.feature_names)
df["target"]=pd.Series(Data.target)

In [5]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [6]:
df2=df.sample(frac=1)

In [7]:
df2.shape

(569, 31)

In [8]:
hold_on_data=df2.iloc[0:285,:]

In [9]:
hold_on_data.shape

(285, 31)

In [10]:
hold_on_data

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
250        20.94         23.56          138.90     1364.0          0.10070   
502        12.54         16.32           81.25      476.3          0.11580   
119        17.95         20.01          114.20      982.0          0.08402   
427        10.80         21.98           68.79      359.9          0.08801   
400        17.91         21.02          124.40      994.0          0.12300   
..           ...           ...             ...        ...              ...   
356        13.05         18.59           85.09      512.0          0.10820   
182        15.70         20.31          101.20      766.6          0.09597   
269        10.71         20.39           69.50      344.9          0.10820   
352        25.73         17.46          174.20     2010.0          0.11490   
88         12.36         21.80           79.78      466.1          0.08772   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
250           0.16060         0.27120              0.13100         0.2205   
502           0.10850         0.05928              0.03279         0.1943   
119           0.06722         0.07293              0.05596         0.2129   
427           0.05743         0.03614              0.01404         0.2016   
400           0.25760         0.31890              0.11980         0.2113   
..                ...             ...                  ...            ...   
356           0.13040         0.09603              0.05603         0.2035   
182           0.08799         0.06593              0.05189         0.1618   
269           0.12890         0.08448              0.02867         0.1668   
352           0.23630         0.33680              0.19130         0.1956   
88            0.09445         0.06015              0.03745         0.1930   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
250                 0.05898  ...          27.00           165.30      2010.0   
502                 0.06612  ...          21.40            86.67       552.0   
119                 0.05025  ...          27.83           129.20      1261.0   
427                 0.05977  ...          32.04            83.69       489.5   
400                 0.07115  ...          27.78           149.60      1304.0   
..                      ...  ...            ...              ...         ...   
356                 0.06501  ...          24.85            94.22       591.2   
182                 0.05549  ...          32.82           129.30      1269.0   
269                 0.06862  ...          25.21            76.51       410.4   
352                 0.06121  ...          23.58           229.30      3234.0   
88                  0.06404  ...          30.50            91.46       574.7   

     worst smoothness  worst compactness  worst concavity  \
250            0.1211             0.3172           0.6991   
502            0.1580             0.1751           0.1889   
119            0.1072             0.1202           0.2249   
427            0.1303             0.1696           0.1927   
400            0.1873             0.5917           0.9034   
..                ...                ...              ...   
356            0.1343             0.2658           0.2573   
182            0.1414             0.3547           0.2902   
269            0.1335             0.2550           0.2534   
352            0.1530             0.5937           0.6451   
88             0.1304             0.2463           0.2434   

     worst concave points  worst symmetry  worst fractal dimension  target  
250               0.21050          0.3126                  0.07849       0  
502               0.08411          0.3155                  0.07538       1  
119               0.11850          0.4882                  0.06111       0  
427               0.07485          0.2965                  0.07662       1  
400               0.19640          0.3245                  0.119

In [11]:
df1=df2.iloc[286:569,:]

In [12]:
y=df1.iloc[:,-1]

In [13]:
y

319    1
160    1
371    1
134    0
360    1
      ..
436    1
73     0
500    1
117    0
424    1
Name: target, Length: 283, dtype: int64

In [14]:
X=df1.iloc[:,:-1]

In [15]:
X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
319       12.430         17.00           78.60      477.3          0.07557   
160       11.750         20.18           76.10      419.8          0.10890   
371       15.190         13.21           97.65      711.8          0.07963   
134       18.450         21.91          120.20     1075.0          0.09430   
360       12.540         18.07           79.42      491.9          0.07436   
..           ...           ...             ...        ...              ...   
436       12.870         19.54           82.67      509.2          0.09136   
73        13.800         15.79           90.43      584.1          0.10070   
500       15.040         16.74           98.73      689.4          0.09883   
117       14.870         16.67           98.64      682.5          0.11620   
424        9.742         19.12           61.93      289.7          0.10750   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
319           0.03454        0.013420             0.016990         0.1472   
160           0.11410        0.068430             0.037380         0.1993   
371           0.06934        0.033930             0.026570         0.1721   
134           0.09709        0.115300             0.068470         0.1692   
360           0.02650        0.001194             0.005449         0.1528   
..                ...             ...                  ...            ...   
436           0.07883        0.017970             0.020900         0.1861   
73            0.12800        0.077890             0.050690         0.1662   
500           0.13640        0.077210             0.061420         0.1668   
117           0.16490        0.169000             0.089230         0.2157   
424           0.08333        0.008934             0.019670         0.2538   

     mean fractal dimension  ...  worst radius  worst texture  \
319                 0.05561  ...         12.90          20.21   
160                 0.06453  ...         13.32          26.21   
371                 0.05544  ...         16.20          15.73   
134                 0.05727  ...         22.52          31.39   
360                 0.05185  ...         13.72          20.98   
..                      ...  ...           ...            ...   
436                 0.06347  ...         14.45          24.38   
73                  0.06566  ...         16.57          20.86   
500                 0.06869  ...         16.76          20.43   
117                 0.06768  ...         18.81          27.37   
424                 0.07029  ...         11.21          23.17   

     worst perimeter  worst area  worst smoothness  worst compactness  \
319            81.76       515.9           0.08409            0.04712   
160            88.91       543.9           0.13580            0.18920   
371           104.50       819.1           0.11260            0.17370   
134           145.60      1590.0           0.14650            0.22750   
360            86.82       585.7           0.09293            0.04327   
..               ...         ...               ...                ...   
436            95.14       626.9           0.12140            0.16520   
73            110.30       812.4           0.14110            0.35420   
500           109.70       856.9           0.11350            0.21760   
117           127.10      1095.0           0.18780            0.44800   
424            71.79       380.9           0.13980            0.13520   

     worst concavity  worst concave points  worst symmetry  \
319         0.022370               0.02832          0.1901   
160         0.195600               0.07909          0.3168   
371         0.136200               0.08178          0.2487   
134         0.396500               0.13790          0.3109   
360         0.003581               0.01635          0.2233   
..               ...                   ...             ...   
436         0.071270               0.06384         

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [17]:
X

array([[-0.45812445, -0.50612584, -0.52500635, ..., -1.26314632,
        -1.55258795, -1.40060544],
       [-0.64787326,  0.26512088, -0.62588137, ..., -0.4950132 ,
         0.50292059, -0.21426071],
       [ 0.31203247, -1.42531611,  0.24366129, ..., -0.4543144 ,
        -0.60189497, -0.91913999],
       ...,
       [ 0.27017611, -0.56918375,  0.2872393 , ..., -0.15141849,
        -1.10482129,  0.11018003],
       [ 0.22273891, -0.58616088,  0.2836078 , ...,  1.37516475,
         1.1794376 ,  1.32308041],
       [-1.20819033,  0.00803864, -1.19764097, ..., -0.99731809,
         0.54834619, -0.20156019]])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [19]:
lr.fit(X_train,y_train)
dt.fit(X_train,y_train)
bn.fit(X_train,y_train)

BernoulliNB()

In [20]:
h_X=hold_on_data.iloc[:,:-1]
h_y=hold_on_data.iloc[:,-1]

In [21]:
h_X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
250        20.94         23.56          138.90     1364.0          0.10070   
502        12.54         16.32           81.25      476.3          0.11580   
119        17.95         20.01          114.20      982.0          0.08402   
427        10.80         21.98           68.79      359.9          0.08801   
400        17.91         21.02          124.40      994.0          0.12300   
..           ...           ...             ...        ...              ...   
356        13.05         18.59           85.09      512.0          0.10820   
182        15.70         20.31          101.20      766.6          0.09597   
269        10.71         20.39           69.50      344.9          0.10820   
352        25.73         17.46          174.20     2010.0          0.11490   
88         12.36         21.80           79.78      466.1          0.08772   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
250           0.16060         0.27120              0.13100         0.2205   
502           0.10850         0.05928              0.03279         0.1943   
119           0.06722         0.07293              0.05596         0.2129   
427           0.05743         0.03614              0.01404         0.2016   
400           0.25760         0.31890              0.11980         0.2113   
..                ...             ...                  ...            ...   
356           0.13040         0.09603              0.05603         0.2035   
182           0.08799         0.06593              0.05189         0.1618   
269           0.12890         0.08448              0.02867         0.1668   
352           0.23630         0.33680              0.19130         0.1956   
88            0.09445         0.06015              0.03745         0.1930   

     mean fractal dimension  ...  worst radius  worst texture  \
250                 0.05898  ...         25.58          27.00   
502                 0.06612  ...         13.57          21.40   
119                 0.05025  ...         20.58          27.83   
427                 0.05977  ...         12.76          32.04   
400                 0.07115  ...         20.80          27.78   
..                      ...  ...           ...            ...   
356                 0.06501  ...         14.19          24.85   
182                 0.05549  ...         20.11          32.82   
269                 0.06862  ...         11.69          25.21   
352                 0.06121  ...         33.13          23.58   
88                  0.06404  ...         13.83          30.50   

     worst perimeter  worst area  worst smoothness  worst compactness  \
250           165.30      2010.0            0.1211             0.3172   
502            86.67       552.0            0.1580             0.1751   
119           129.20      1261.0            0.1072             0.1202   
427            83.69       489.5            0.1303             0.1696   
400           149.60      1304.0            0.1873             0.5917   
..               ...         ...               ...                ...   
356            94.22       591.2            0.1343             0.2658   
182           129.30      1269.0            0.1414             0.3547   
269            76.51       410.4            0.1335             0.2550   
352           229.30      3234.0            0.1530             0.5937   
88             91.46       574.7            0.1304             0.2463   

     worst concavity  worst concave points  worst symmetry  \
250           0.6991               0.21050          0.3126   
502           0.1889               0.08411          0.3155   
119           0.2249               0.11850          0.4882   
427           0.1927               0.07485          0.2965   
400           0.9034               0.19640          0.3245   
..               ...                   ...             ...   
356           0.2573               0.12580         

In [22]:
h_X=sc.fit_transform(h_X)

In [23]:
x1=lr.predict(h_X)
x2=dt.predict(h_X)
x3=bn.predict(h_X)

In [24]:
x1

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1])

In [25]:
x2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1])

In [26]:
x3

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [27]:
df3=pd.DataFrame(data=[x1,x2,x3])

In [28]:
df4=df3.T

In [29]:
df4

0  1  2
0    0  0  0
1    1  1  1
2    0  0  0
3    1  1  1
4    0  0  0
..  .. .. ..
280  1  1  1
281  0  0  0
282  1  1  1
283  0  0  0
284  1  1  1

[285 rows x 3 columns]

In [30]:
lr2=LogisticRegression()

In [31]:
df4_X=df4.iloc[:,:]
df4_Y=h_y

In [32]:
df4_X

0  1  2
0    0  0  0
1    1  1  1
2    0  0  0
3    1  1  1
4    0  0  0
..  .. .. ..
280  1  1  1
281  0  0  0
282  1  1  1
283  0  0  0
284  1  1  1

[285 rows x 3 columns]

In [33]:
df4_Y

250    0
502    1
119    0
427    1
400    0
      ..
356    1
182    0
269    1
352    0
88     1
Name: target, Length: 285, dtype: int64

In [34]:
lr2.fit(df4_X,df4_Y)

LogisticRegression()

In [35]:
X_test=sc.fit_transform(X_test)

In [36]:
X_test

array([[-0.78756068, -0.94635277, -0.80334247, ..., -0.54583436,
        -0.38110636, -1.07864903],
       [ 0.3211177 , -1.30582538,  0.2764231 , ...,  0.18749546,
        -0.31237435, -0.90019257],
       [-0.8290066 , -0.91926922, -0.79140312, ..., -0.57425367,
        -1.14008316,  1.05874608],
       ...,
       [-0.1114741 , -0.80108644, -0.17951109, ..., -0.68834887,
        -0.30944959, -0.80513243],
       [-1.62528636, -0.5893423 , -1.59992143, ..., -1.3694373 ,
         0.24625597, -0.70307401],
       [-0.52852367, -0.54994804, -0.59664236, ..., -1.33210212,
        -1.51445323, -1.56444715]])

In [37]:
x4=lr.predict(X_test)
x5=dt.predict(X_test)
x6=bn.predict(X_test)

In [38]:
df5=pd.DataFrame(data=[x4,x5,x6])

In [39]:
df6=df5.T

In [40]:
df6

0  1  2
0   1  1  1
1   1  0  0
2   1  1  1
3   0  0  0
4   0  0  0
.. .. .. ..
89  0  0  0
90  1  1  1
91  1  1  1
92  1  1  1
93  1  1  1

[94 rows x 3 columns]

In [41]:
df6_X=df6.iloc[:,:]


In [42]:
final=lr2.predict(df6_X)

In [43]:
from sklearn.metrics import accuracy_score

In [44]:
accuracy_score(y_test, final)


0.9361702127659575

In [45]:
precision = precision_score(y_test, final, average=None)
recall = recall_score(y_test, final, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.94871795 0.92727273]
recall: [0.90243902 0.96226415]


In [46]:
from sklearn.ensemble import StackingClassifier

In [47]:
df_X=df.iloc[:,:-1]
df_y=df.iloc[:,-1]

In [48]:
df_X=sc.fit_transform(df_X)

In [49]:
df_X.shape

(569, 30)

In [50]:
df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(df_X, df_y, test_size=0.33)

In [51]:
estimators=[('lr',LogisticRegression()),('dt',DecisionTreeClassifier()),('bn',BernoulliNB())]

In [52]:
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

In [53]:
clf.fit(df_X_train,df_y_train)

StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('dt', DecisionTreeClassifier()),
                               ('bn', BernoulliNB())],
                   final_estimator=LogisticRegression())

In [54]:
final1=clf.predict(df_X_test)

In [55]:
accuracy_score(df_y_test, final1)

0.9893617021276596

In [56]:
precision = precision_score(df_y_test, final1, average=None)
recall = recall_score(df_y_test, final1, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.98412698 0.992     ]
recall: [0.98412698 0.992     ]
